---
name: "☁️ GCP Action"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <staging|production>"
        required: false
        default: "staging"

  push:
    branches: [main]
    paths: [gcs/**, .github/workflows/gcp-action.yml]
    
jobs:
  job_id:
    if: github.repository == 'ss-o/gcp'
    name: "🆙 GCP"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: "actions/checkout@v3"

      # ℹ️ https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
      - name: "🔒 Workload Identity Federation"
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "${{ secrets.DIGITAL_CLOUDS_PROVIDER }}"
          service_account: "${{ secrets.DIGITAL_CLOUDS_SERVICE }}"

      # ℹ️ https://github.com/google-github-actions/setup-gcloud#cloud-sdk-inputs
      - name: "⚙️ Google Cloud SDK"
        id: "setup-gcloud"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: "Run gcloud CLI"
        run: "gcloud info"

      # ℹ️ https://github.com/google-github-actions/ssh-compute#inputs
      #- name: "SSH to GCP compute instances"
      #  id: "compute-ssh"
      #  uses: "google-github-actions/ssh-compute@v0"
      #  with:
      #    instance_name: "e2"
      #    zone: "${{ secrets.COMPUTE_ZONE }}"
      #    ssh_private_key: "${{ secrets.GCP_SSH_PRIVATE_KEY }}"
      #    command: "echo Hello world"
      #- id: "test"
      #  run: |-
      #    echo '${{ steps.compute-ssh.outputs.stdout }}'
      #    echo '${{ steps.compute-ssh.outputs.stderr }}'

      # ℹ️ https://github.com/google-github-actions/upload-cloud-storage#upload-cloud-storage
      - name: "📤 Upload to (GCS)"
        id: "upload-assets"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "gcs/5f0326f2-f9c1-4d47-9772-af81d4a948de"
          destination: "digital-space"
      - id: 'uploaded'
        uses: 'ss-o/gcp/.github/workflows/gcp-action@main'
        env:
          files: '${{ steps.upload-assets.outputs.uploaded }}'
